apiVersion: v1
kind: Service
metadata:
  name: longhorn-nodeport
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
    nodePort: 31000
  selector:
    app: longhorn-ui
